name: PHPStan

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'
      - '.github/workflows/phpstan.yml'

jobs:
  phpstan:
    name: phpstan
    runs-on: arc-runner-set-05cpu-1g
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
        env:
          runner: self-hosted

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: PHPStan Static Analysis
        run: vendor/bin/phpstan analyse --configuration=phpstan.neon.dist --memory-limit=256M --no-progress --no-interaction
