name: Dru^ID CI
on: [push]

jobs:
  druid-ci:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:10.5.8
        env:
          MYSQL_DATABASE: druid_test
          MYSQL_USER: druid_test
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 32574:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      # Setup
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          coverage: none

      - uses: actions/checkout@v2

      # Preparing environment
      - name: Installing PHP dependencies
        run: |
          composer clear-cache
          composer install
          composer dump-autoload

      # Tests migrations
      - name: Testing migrations
        run: |
          ./vendor/bin/testbench migrate:fresh
          ./vendor/bin/testbench migrate
        env:
          DB_PORT: 32574

      - name: Running phpstan
        run: ./vendor/bin/phpstan analyse -c phpstan.neon

      - name: Delete old data from database before tests
        run: ./vendor/bin/testbench db:wipe
        env:
          DB_PORT: 32574

      - name: Running phpunit
        run: ./vendor/bin/phpunit --no-coverage
        env:
          DB_PORT: 32574

      # On failure
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_COLOR: '#FF5555'
          SLACK_USERNAME: 'Drui^ID CI'
          SLACK_ICON_EMOJI: ':hinhin:'
          SLACK_TITLE: Dernier commit
          SLACK_FOOTER: "“Je ne comprends pas, pourtant ça marche en local.” — inconnu"
